# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 514df782a4ed99de2da029c2b0e269375f4d0ba63ef885a6a0f131b0f34acd6fd5728ab025e3a95a09d46c69ac09140abd63109e71b67c132fa55e2513cfc4d2

test:
  secret_key_base: 32d80495c49ea1b52bb2b8733277603f5d5d54d6c5296f06ea7a7d995880da20baaba15440a99f2d533c3929e921fd6e7a3c89ff4425f9663728ed1ac23afd38

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
